[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  
[[redirects]]
  from = "/zatmeni"
  to = "https://youtu.be/3XJz9aw2k4k"
  status = 301

[[redirects]]
  from = "/beta"
  to = "https://deploy-preview-3--itoncek.netlify.app/"
  status = 301
  
[[redirects]]
  from = "/zatmeni"
  to = "https://youtu.be/3XJz9aw2k4k"
  status = 301
    
[[redirects]]
  from = "/oxikomania"
  to = "https://discord.gg/wG9trXHZBv"
  status = 301
   
[[redirects]]
  from = "/sts107"
  to = "https://astrocrew.itoncek.cf/sts107/"
  status = 301
    
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/@ajtoncek"
  status = 301
  
[[redirects]]
  from = "/scenar_old"
  to = "https://1url.cz/v1Je0"
  status = 301
  
[[redirects]]
  from = "/scenar"
  to = "https://cdn.itoncek.space/scenar_new.pdf"
  status = 301
  
[[redirects]]
  from = "/scenar_html"
  to = "https://cdn.itoncek.space/scenar_new.html"
  status = 301
  
[[redirects]]
  from = "/scenar_fdx"
  to = "https://cdn.itoncek.space/scenar_new.fdx"
  status = 301
  
[[redirects]]
  from = "/nlcmonitor.ps1"
  to = "https://github.com/MadeByIToncek/NLCMonitor/raw/master/install.ps1"
  status = 200

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.114.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.114.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.114.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.114.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 301
